### ISSUE TITLE
Precedence error

### ISSUE THREAD

**Issue by janhohenheim** [maxhauser/semver#26]
[semver.org rule 11](https://semver.org/#spec-item-11) shows the following example:  
`1.0.0-beta.11 < 1.0.0-rc.1`  
`CompareByPrecedence` however doesn't follow this.

**Comment by jnferner** [comment]
ping @maxhauser

**Comment by WalkerCodeRanger** [comment]
`CompareByPrecedence` returns `-16` when comparing `1.0.0-beta.11` to `1.0.0-rc.1`. In fact, so does `CompareTo`. This behavior is technically correct because the docs state that it returns "Less than zero" for "This object precedes the object specified by the CompareTo method in the sort order."

However, I agree this behavior is surprising because in all other cases it returns -1, 0, or 1. I think this should be improved in a future version.

**Comment by WalkerCodeRanger** [comment]
In v2.2.0, the `CompareByPrecedence` method has been marked `[Obsolete]`. The new `ComparePrecedenceTo` and all other new comparison methods always return -1, 0, or 1.
