### ISSUE TITLE
Migrate to .NET Standard 2.0

### ISSUE THREAD

**Issue by WalkerCodeRanger** [maxhauser/semver#30]
Migrate to .NET Standard 2.0 and stop multi-targeting.

Versions 2.x target .NET Standard 1.1 and .NET Framework 4.5.2. This is needed to offer serialization support on the .NET Framework side. `ISerializable` is supported in .NET Standard beginning with .NET Standard 2.0 ([ISerializable Interface](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable#applies-to)). .NET Standard 2.0 is only supported back to .NET Framework  4.6.1, though 4.7.2 is recommended ([.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)).

Moving to .NET Standard 2.0 would be a breaking change because it would drop support for frameworks supported by 1.1 but not 2.0. Likewise, not multi-targeting would be a breaking change because it would drop support for .NET Framework versions 4.5.2 up to 4.6.0.

**Comment by WalkerCodeRanger** [comment]
Having thought about this more, it may make sense to keep backward compatibility longer. It is currently a low impact on the code.

**Comment by khellang** [comment]
It would be great if this could happen sooner than later, possibly by adding an extra `netstandard2.0` target. Because earlier versions of .NET Standard relies on the `NETStandard.Library` dependency, we're getting a lot of security warnings, like this:

![image](https://user-images.githubusercontent.com/582487/145997445-eb69ad2b-e1bf-486f-94ec-c4be08e326ca.png)

By simply adding a new `netstandard2.0` target, this dependency would go away for all targets that support `netstandard2.0`, which is probably most of the ecosystem by now.

**Comment by WalkerCodeRanger** [comment]
I have decided to make this issue cover only adding the .NET Standard 2.0 target and have added issue #68 Drop Support for Older .NET Versions for the breaking change of removing older framework support when releasing the next major version.
