### ISSUE TITLE
Snyk Security Issue

### ISSUE THREAD

**Issue by garethf89** [maxhauser/semver#58]
Maybe this is just me being silly (new to .NET) but Snyk seems to be reporting a vulnerability in the package however the link below tells me to upgrade to 4.3.2, which does not exist as the latest is 2.0.5. Can you advise me on this issue? 

Thanks,
Gareth.

Medium severity vulnerability found in Semver
  Description: Regular Expression Denial of Service (DoS)
  Info: https://snyk.io/vuln/SNYK-DOTNET-SEMVER-60208
  Introduced through: Semver@2.0.5

![Screenshot 2019-12-10 at 16 05 33](https://user-images.githubusercontent.com/5473451/70546293-eb81fc00-1b66-11ea-903a-0b40391a5ccf.png)

**Comment by WalkerCodeRanger** [comment]
That is very strange. I'm not familiar with Snyk myself. However, it seems like the vulnerability may have been incorrectly entered or at least the details incorrectly copied from another vulnerability. The `semver` npm package has a vulnerability reported on it https://snyk.io/vuln/npm:semver:20150403 That one contains a lot of the same text and suggests the same version upgrade. However, the Semver NuGet package is entirely independent of the npm package. It is common to create NuGet packages from npm packages so it is possible they assumed this was done because the names matched.

That said, this package does use RegEx in parsing and there have apparently been some issues with RegEx DoS attacks in .NET. See http://blog.malerisch.net/2015/09/net-mvc-redos-denial-of-service-vulnerability-cve-2015-2526.html for discussion of one. For a general discussion of the ReDoS attack see Wikipedia https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS See https://www.regular-expressions.info/redos.html for discussion of how to mitigate the ReDoS attack.

For this issue, I'll investigate:
1. Whether the Semver package is susceptible to ReDoS
2. If it is, how that can be mitigated. (A complete overhaul of parsing is planned for v2.1.0, but the old parsing won't be entirely removed until breaking changes in v3.0.0)
3. Working with Snyk to make sure their database correctly reflects the status of the Semver NuGet package.

It sounds like users can mitigate this issue in the meantime by placing a length limit on version strings. Given that you are using the package indirectly through Umbraco I don't know whether that is feasible for you or not.

**Comment by garethf89** [comment]
Thanks for the quick response! Yeah you are right I am not directly using the package so i can't control this, however it does look like it could just be mistake on Snyk with the NPM package.

**Comment by WalkerCodeRanger** [comment]
For reference the exact RegEx used in v2.0.5 is:
```regex
^(?<major>\d+)(\.(?<minor>\d+))?(\.(?<patch>\d+))?(\-(?<pre>[0-9A-Za-z\-\.]+))?(\+(?<metadata>[0-9A-Za-z\-\.]+))?$
```

I found [redos-checker.surge.sh](https://redos-checker.surge.sh/) ([github project](https://github.com/gagyibenedek/ReDoS-checker)) which claims this RegEx is vulnerable. I'm not sure whether to trust it because I don't know exactly what RegEx syntax it supports. Reviewing the regex myself, I see nested repetition only in the sense that there is repetition inside of optional sections. I don't know whether that is a problem or not. The [OWASP discussion of ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) gives `(.*a){x}` for x > 10 as an example of a problem regex. Since optional is a single repetition, that makes me think it isn't a problem.

It looks like it may make sense to add some atomic groups to the RegEx and a match timeout to be safe.

**Comment by WalkerCodeRanger** [comment]
v2.0.6 has been released with changes that should mitigate the possibility of ReDoS attacks. Note that I was not able to demonstrate an actual issue in the previous version.

I'll be trying to get in contact with Snyk next to see if I can get their site updated to reflect this.

**Comment by WalkerCodeRanger** [comment]
For reference, these are the relevant lines for the changes. This shows both the modified RegEx and the added parsing timeout.
https://github.com/maxhauser/semver/blob/9398386011b84642e5da0c17b681ecfd6d79d81c/Semver/SemVersion.cs#L24-L34

**Comment by WalkerCodeRanger** [comment]
I have been in contact with Snyk and they said they will fix the DB. I see that the [page for the semver NuGet package](https://snyk.io/vuln/SNYK-DOTNET-SEMVER-60208) now states at the  top "Amendment: This was deemed not a vulnerability." Between that and the release of v2.0.6 with ReDoS mitigation, I'm considering this resolved.
