### ISSUE TITLE
Is there support planned for parsing version with build numbers?

### ISSUE THREAD

**Issue by pri-kise** [maxhauser/semver#62]
I had the problem that I tried to parse an verision with a build number, e.g. ``16.2.34.0`, that resulted in the non helpfull error `Invalid version`.

Maybe this exception could be improved to include the string that was tryed to parse.

**Comment by WalkerCodeRanger** [comment]
Parsing 4 part version numbers won't be supported since they don't follow the SemVer standard. However, it would be good to have a better error message. Especially for version numbers like this that can be reasonably expected given they are used commonly.

Version 2.1.0 of the package is meant to overhaul the parsing. Giving detailed exception messages is a little awkward when trying to support efficient `TryParse` as well. I'll look into what can be done.

There is currently no timeline for the release of v2.1.0

**Comment by WalkerCodeRanger** [comment]
In v2.1.0 of the SemVer package, the new parse methods will throw a `FormatException` with the message `Fourth version number in '{0}'.`
